### ISSUE TITLE
Default test folder and grunt tasks

### ISSUE THREAD

**Issue by LoveIsGrief** [balderdashy/sails-generate-new#10]
Hi,

It'd be great if the generator include the test-folder structure for mocha as described in the [docs](http://sailsjs.org/#/documentation/concepts/Testing).

Not only would a test-folder structure be nice, but also grunt tasks to be able to run `grunt test` e.g

`tasks/conf/mocha.js`:
```javascript
module.exports = function(grunt) {

  grunt.initConfig({
    // Configure a mochaTest task
    mochaTest: {
      test: {
        options: {
          reporter: 'spec',
        },
        src: ['test/**/*.js']
      }
    }
  });

  // Add the grunt-mocha-test tasks.
  grunt.loadNpmTasks('grunt-mocha-test');
};
```

`tasks/register/test.js`:
```javascript
module.exports = function(grunt) {

  grunt.registerTask('test', 'mochaTest');

};
```

**Comment by rachaelshaw** [comment]
Sounds great!  Have you seen https://github.com/balderdashy/sails-generate-test?

**Comment by rachaelshaw** [comment]
Once that generator is ready to go, we can call out to it from this one.  re: grunt testing stuff, that's something that could be generated as part of sails-generate-test as well.  Hope that helps-- if you'd like to contribute something along these lines, that'd be awesome :)
