### ISSUE TITLE
--no-frontend doesn't work

### ISSUE THREAD

**Issue by anthonator** [balderdashy/sails-generate-new#8]
I was trying to create a frontend-less project and attempted to use ```--no-frontend``` as described in https://github.com/balderdashy/sails-generate-new/pull/2.

Command:

```./node_modules/.bin/sails new --no-frontend my-new-project```

Error:

````sails new` can only be called on an empty directory.```

I did ensure that ```my-new-project``` didn't exist before running the command.

**Comment by davidhughes85** [comment]
You have to move `--no-frontend` to the end of the command.

`sails new my-new-project --no-frontend`
